

"""
Django settings for krishipath project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-x220h&s18h-wg%(5445(-nl!cp*0ex#u$#1^t=3lo1yhpw41!s'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'logins',   # Login/Register Page
    'Home',     # Home Page
    'advisory',
    # For google login
    'allauth',  # Authentication
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'social_django',  # For social authentication


    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',


]

# For google login authentication
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',        # Default Backend
    'allauth.account.auth_backends.AuthenticationBackend',  
    'social_core.backends.google.GoogleOAuth2',  # Google OAuth2 Backend
    'django.contrib.auth.backends.ModelBackend',  # Remote User Backend

]

EMAIL_BACKEND = [
    'django.core.mail.backends.console.EmailBackend',
    'django.core.mail.backends.smtp.EmailBackend'
]

SITE_ID = 2



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'social_django.middleware.SocialAuthExceptionMiddleware',  # For social authentication
]

ROOT_URLCONF = 'krishipath.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'social_django.context_processors.backends',
                'social_django.context_processors.login_redirect',
            ],
        },
    },
]

WSGI_APPLICATION = 'krishipath.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': '440610155211-o1t39e264s9qcghl63nm7ojf12l59s9a.apps.googleusercontent.com',
            'secret': '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',
            'key': ''
        },

        'SCOPE': [ 'profile', 'email',],

        'AUTH_PARAMS': {
            'access_type': 'online',
        },

        'METHOD': 'oauth2',
        'VERIFIED_EMAIL': True
    }
}




# For Google Login/Register/Logout

LOGIN_URL = '/logins/login/'  # or wherever you want to redirect for login

# LOGIN_REDIRECT_URL = '/logins/register/'  # or wherever you want to redirect after login    
LOGOUT_REDIRECT_URL = '/logins/register/'  
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
ACCOUNT_SIGNUP_REDIRECT_URL = '/logins/register/'  # or wherever you want to redirect after signup

ACCOUNT_ADAPTER = 'logins.adapter.CustomAccountAdapter' 



# For sending email using Gmail SMTP

DEBUG = True
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'krishipath7@gmail.com'
# EMAIL_HOST_USER = 'omjoshi424566@gmail.com'

# EMAIL_HOST_PASSWORD = 'ttzm xdqn eojh tubo'  
EMAIL_HOST_PASSWORD = 'lpexdphcqlyvxnib'
# EMAIL_HOST_PASSWORD = 'lpex dphc qlyv xnib'  

DEFAULT_FROM_EMAIL = 'krishipath7@gmail.com'





EMAIL_FAIL_SILENTLY = False
PASSWORD_RESET_TIMEOUT = 180
